name: Generate Thrift Code

on:
  push:
    branches:
      - develop  
  pull_request:
    branches:
      - develop 

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  

      - name: Install Thrift
        run: |
          sudo apt-get install -y thrift-compiler
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run generate.sh
        run: |
          chmod +x ./generate.sh  
          ./generate.sh
      - name: Commit and push generated files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add soccer/*
          git commit -m "Automated update: Generated Thrift classes"
          git push origin develop
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
